### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by noahmay**
The project currently has no license.  Since this should be an open-source project we need to add one.

All previous contributors need to state that they agree to the license and that the license applies to their previous contributions.

### CODE REVIEW

**Comment by LucasBoberg** [comment]
I agree

**Comment by emilwihlander** [comment]
I agree

**Comment by noahmay** [comment]
I agree

**Comment by TheJarles** [comment]
I agree

**Comment by kuleshmaria** [comment]
I agree

**Comment by Isak-Evaldsson** [comment]
I agree

**Comment by theolundqvist** [comment]
I agree

**Review by emilwihlander — APPROVED** [review]

**Pull request merged**
