### PR TITLE
💄 #637 make articles take up less space

### PR DESCRIPTION
**Pull request by Macludde**
Waiting for short_description (I think)

### CODE REVIEW

**Comment by Macludde** [comment]
Aside from some structural and design changes, this PR no longer truncates articles by cutting it off after X characters and replacing the rest with an ellipsis (...), it instead cuts of the div with max height and fades out the last part with an opacity gradient mask.

The reason behind this was an issue which I noticed where if a post includes a lot of whitespace (which count for no, or very few characters) the cut-off would not be reasonable.

Try for example creating a post with the following content with a single character followed by a blank line, repeated 200-300 times, as follows:
`a

a

a

etc...`

**Comment by Macludde** [comment]
Will fix lint issues

**Review by oliverlevay — APPROVED** [review]
Beautiful! 🎇

**Comment by oliverlevay** [comment]
> Aside from some structural and design changes, this PR no longer truncates articles by cutting it off after X characters and replacing the rest with an ellipsis (...), it instead cuts of the div with max height and fades out the last part with an opacity gradient mask.
> 
> The reason behind this was an issue which I noticed where if a post includes a lot of whitespace (which count for no, or very few characters) the cut-off would not be reasonable.
> 
> Try for example creating a post with the following content with a single character followed by a blank line, repeated 200-300 times, as follows:
> 
> ```
> a
> 
> a
> 
> a
> 
> etc...
> ```

This is a much better solution than we had before. This is what we wanted to do but we weren't skilled enough 😅

**Pull request merged**
